### ISSUE TITLE
The support for werft should either be optional or excluded

### ISSUE THREAD

**Issue by wulfthimm** [gitpod-io/observability#24]
**Update 26-11-2021:** Blocked by #34 

The observability stack assumes that every installation has werft deployed and applying will lead to resources failing because of a missing namespace.

**Comment by meysholdt** [comment]
Can you name the resources that are failing?

**Comment by wulfthimm** [comment]
[Here is an example](https://argo-cd.gitpod-io-dev.com/applications/prod-ws-eu18-monitoring-satellite?conditions=false&resource=&operation=false) of a failing deployment where werft is missing. It is a workspace-nodepool.

**Comment by mads-hartmann** [comment]
@wulfthimm or @ArthurSens could you outline what it would take to solve this issue in rough steps. That will help me figure out whether this is something we want to prioritise now.

**Comment by ArthurSens** [comment]
The problem makes perfect sense!

To be able to monitor werft, monitoring-satellite depends on a couple of resources that are deployed in the same namespace where werft lives (ServiceMonitors, NetworkPolicies, etc). It works fine with any cluster where werft's namespace exists, but it is only one cluster between several that we run monitoring-satellite.

It didn't cross my mind that Argo would fail if that namespace didn't exists, but thinking again now it is kinda obvious 🤦‍♂️. We should probably put all werft resources behind a external variable, which is unfortunate because it is yet another breaking change and will require a couple of extra PRs downstream that updates all monitoring-satellites

**Comment by mads-hartmann** [comment]
@ArthurSens The situation with extVars is indeed quite problematic, especially when Workspace starts consuming monitoring-satellite using jsonnet 😕  

I have created an issue https://github.com/gitpod-io/observability/issues/34 and added it to our discussion for the next Platform meeting.

I'm marking this as blocked for now as I think we should decide on the above issue first.
