### ISSUE TITLE
Find a way to introduce new extVars in a backwards compatible way

### ISSUE THREAD

**Issue by mads-hartmann** [gitpod-io/observability#34]
jsonnet [deliberately doesn't support default values for external variables](https://github.com/google/go-jsonnet/issues/247#issuecomment-425662159) which means that whenever we introduce a new `extVar` we will break all existing invocations. So at the moment you have to introduce the `extVar` everywhere (jsonnet will happily ignore unused `extVar`s) before you start using it in your templates.

Right now that's annoying but tolerable as we own all invocations of our jsonnet templates. But soon (maybe already) that isn't the case as the Workspace team will start consuming them.

We have a few options (currently we favour option 3)

1. Accept that introducing extVars is a breaking change. All users of our templates should then point to a fixed SHA of this repository and we can maintain a CHANGELOG that consumers can look at when upgrading.
2. Introduce an indirection: We publish a shell script (as the repo is public people can just use the Git url) which takes all extVars as parameters and can thus pick default values and then invoke our jsonnnet templates with all extVars set.
3. **Use a json configuration file (later it can be YAML once jsonnet supports it) that our jsonnet programs loads. That file becomes the configuration surface and our jsonnet programs can provide default values as needed.**

**Comment by mads-hartmann** [comment]
Adding `Pending clarification` as we will discuss this in the Platform team

**Comment by ArthurSens** [comment]
I've spent some minutes looking into alternatives and found out about `top level arguments`.

It would require some good refactoring and experimentation, but I think the final result will become pretty nice.

From what I understood, we would change monitoring-satellite.libsonnet and monitoring-central.libsonnet to become a function, instead of just a JSON with overrides everywhere.

This comment here was the convincing argument for me 🙂 https://github.com/google/jsonnet/issues/757#issuecomment-572484048.

Grafonnet also implements everything related to Grafana dashboards this way, I'm impressed this has never crossed my mind before 😅

For example the [library that creates a Stats Panel](https://github.com/grafana/grafonnet-lib/blob/master/grafonnet/stat_panel.libsonnet). A function can have as many arguments as needed and they all have their defaults. When calling the function from the command line, we can override the defaults values by setting e.g. `--tla-str tracing_enabled=true`

**Comment by ArthurSens** [comment]
The refactoring will be quite big though, we'll need to rewrite almost the whole repository

**Comment by mads-hartmann** [comment]
Based on our discussions:

1. I have created a new issue to fix the git SHA everywhere so that we can introduce breaking changes and then go through all installations and update them accordingly https://github.com/gitpod-io/observability/issues/39
2. I have updated the description to include a 3rd option and marked it a favourable. The issue will continue to be unscheduled for now.

**Comment by ArthurSens** [comment]
It is still not clear to me where this json file will live 🤔.

Every ArgoCD app is configured with different variables, which means they will need different configuration files. Where do we put them? How does argo loads them?

**Comment by mads-hartmann** [comment]
@meysholdt You suggested the config option, would you be able extend a bit on your suggestion here? ☺️

**Comment by ArthurSens** [comment]
I'm investigating this a little further and I think my suggestion with top-level-arguments does work but requires quite a big effort sorting things out... I'd say ~1week of work 😬.


Using a JSON config file would be easier if we can figure out how that  would work with ArgoCD

**Comment by meysholdt** [comment]
hi @ArthurSens, I can help with this.

**Comment by meysholdt** [comment]
Can we simply embed it into the ArgoCD Manifest?

e.g.

```
source:
    directory:
      jsonnet:
        extVars:
          - name: config_stirng
            value: |
                 {
                    "cluster_name": "prod-meta-us01",
                    "namespace": "cluster-monitoring"
                    .....
                 }
```

**Comment by ArthurSens** [comment]
> Can we simply embed it into the ArgoCD Manifest?
> 
> e.g.
> 
> ```
> source:
>     directory:
>       jsonnet:
>         extVars:
>           - name: config_stirng
>             value: |
>                  {
>                     "cluster_name": "prod-meta-us01",
>                     "namespace": "cluster-monitoring"
>                     .....
>                  }
> ```

I'm making some tests here and I confirm that this strategy works! Opening a draft PR soon!
